### ISSUE TITLE
"Type string led to invalid type"

### ISSUE THREAD

**Issue by alexanderkoller** [coli-saar/am-tools#9]
I get the following error message, which can be easily reproduced on the servers. Is this because of a change in the type format?

```
falken-1:~/workspace/am-tools$ java -Xmx100G -cp build/libs/am-tools.jar de.saar.coli.irtg.experimental.astar.Astar  -s /proj/irtg.shadow/EMNLP20/AMR-2017/dev/single-bert/scores.zip
Reading supertags ...
Exception in thread "main" java.lang.IllegalArgumentException: Type string led to invalid type: TOP(o(poss_UNIFY_s),o2(s_UNIFY_o),s)
	at de.up.ling.irtg.algebra.graph.ApplyModifyGraphAlgebra$Type.<init>(ApplyModifyGraphAlgebra.java:245)
	at de.up.ling.irtg.algebra.graph.ApplyModifyGraphAlgebra$Type.<init>(ApplyModifyGraphAlgebra.java:236)
	at de.saar.coli.irtg.experimental.astar.Astar.main(Astar.java:729)
```

@jgroschwitz Could you have a look at this?

**Comment by jgroschwitz** [comment]
yes, this is because we switched from the old IWCS type system to the more consistent one of my thesis. But the data you're working with still has the old types. How should we handle this? Can we just handle it locally in the application (here the A* parser)?
